version: '3.8'
name: vote_project

services:
  postgres:
    image: postgres:16.3
    restart: always
    container_name: postgress
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data
    entrypoint: >
      sh -c "chmod +x /docker-entrypoint-initdb.d/db_init.sh && exec docker-entrypoint.sh postgres"
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file: .env
  bot:
    container_name: bot
    image: node:20
    working_dir: /app
    volumes:
      - ../bot-service:/app
    ports:
      - "5012:5012"
    command: sh -c "npm install && npm run start"
    depends_on:
      - postgres

volumes:
  postgres-data:
